name: Reproduce
on:
  push:
    branches:
      - ci/package-fill

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  SOURCE_DATE_EPOCH: 0
  BUILD_ENV: ghcr.io/${{ github.repository }}/build-env:latest

jobs:
  publish-test:
    name: Publish Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # build test
    outputs:
      digest: ${{ steps.publish.outputs.digest }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: .github/actions
          sparse-checkout-cone-mode: true

      - name: Publish test
        id: publish
        uses: ./.github/actions/publish-env
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          image: ${{ github.repository }}/test-env
          file: test/Dockerfile
          target: artifact
          build-args: |
            ENV_IMAGE=${{ env.BUILD_ENV }}