name: Secret Scan (PR)

on:
  pull_request:

permissions:
  contents: read

jobs:
  secret-scan:
    uses: enclaive/security-workflows/.github/workflows/trufflehog-pr.yml@9947876faac0881135b22291d5f88e700a51e209 # v1
    secrets:
      MM_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
