name: Secret Scan (PR)

on:
  pull_request:

permissions:
  contents: read

jobs:
  secret-scan:
    uses: enclaive/security-workflows/.github/workflows/trufflehog-pr.yml@v1
    secrets:
      MM_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
